### ISSUE TITLE
Introduce environment variables for MaxMessageSize and MaxGroupSize settings

### ISSUE THREAD

**Issue by jorgebay** [polarstreams/polar#142]
[`MaxMessageSize()` and `MaxGroupSize()` config settings](https://github.com/polarstreams/polar/blob/v0.6.0/internal/conf/config.go#L243-L249) are hardcoded.

We should use environment variables to allow users to set it to the desired size, if needed.

See `MaxSegmentSize()` for example
- https://github.com/polarstreams/polar/blob/v0.6.0/internal/conf/config.go#L37
- https://github.com/polarstreams/polar/blob/v0.6.0/internal/conf/config.go#L311-L313

**Comment by sunilkumardash9** [comment]
I suppose this is what intended to be done

![Screenshot from 2023-02-25 03-31-13](https://user-images.githubusercontent.com/47926185/221347456-3982f618-c19c-4476-bbfc-09f56fb7fbbd.png)
 
![Screenshot from 2023-02-25 03-31-52](https://user-images.githubusercontent.com/47926185/221347465-525f7d38-fd5f-47b2-808c-af17ba65f2eb.png)

**Comment by jorgebay** [comment]
@sunilkumardash9 yeah!

**Comment by sunilkumardash9** [comment]
Would love to contribute

**Comment by jorgebay** [comment]
Sure! I'll assign it to you 👍
